services:
  - type: web
    name: seizi-api
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn wecandoit_back.wsgi --log-file -"
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: seizi
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


    autoDeploy: true